# Aufgabe 10.2

Zwei Tiefen-Messgeräte messen für die Tiefe einer Gesteins-Schicht an 9 verschiedenen Orten die folgenden Werte: Kennzahlen für die Differenz:
¯dn beträgt −5.78, die Standardabweichung σD = 6.2.

| Differenz di 	| -7  	| -16 	| -3  	| 2   	| -1  	| -10 	| -11 	| 2   	| -8  	|
|--------------	|-----	|-----	|-----	|-----	|-----	|-----	|-----	|-----	|-----	|
| Messgerät A  	| 120 	| 265 	| 157 	| 187 	| 219 	| 288 	| 156 	| 205 	| 163 	|
| Messgerät B  	| 127 	| 281 	| 160 	| 185 	| 220 	| 298 	| 167 	| 203 	| 171 	|


Es wird vermutet, dass Gerät B systematisch grössere Werte misst.
Bestätigen die Messwerte diese Vermutung oder ist eine zufällige Schwankung als Erklärung plausibel?

a) Handelt es sich um verbundene (gepaarte) oder um unabhängige Stichproben?

Es handelt sich um gepaarte Stichproben, da die Messgeräte an den gleichen 9 Orten messen.

b) Führen Sie einen t-Test auf dem Niveau α = 0.05 durch. Formulieren Sie explizit:
Modellannahmen, Nullhypothese, Alternative, und Testergebnis.

Modellannahmen:  D1, . . . , Dn i.i.d. ∼ N (µ, σ^2, σ wird durch bσ geschätzt.
Nullhypothese: Die Gerät messen die gleichen Werte
Alternativhypothese: Das Gerät B misst grössere Werte.

```{R}
a <- c(120, 265, 157, 187, 219, 288, 156, 205, 163)
b <- c(127, 281, 160, 185, 220, 298, 167, 203, 171)
t.test(a, b, alternative = "less", mu = 0, paired = T, conf.level = 0.95)
```

Testergebnis: p-value 0.01168 < 0.05 --> Nullhypothese verwerfen
Das bedeutet, dass das Gerät B signifikant grössere Werte misst.
