# Aufgabe 10.3
In der folgenden Tabelle sind die Kieferlängen von 10 männlichen und 10 weiblichen
Goldschakalen eingetragen:

Einige Kennzahlen: x¯n = 113.4, y¯n = 108.6, bσ2x = 13.82,

männlich xi 120 107 110 116 114 111 113 117 114 112
weiblich yj 110 111 107 108 110 105 107 106 111 111
bσ2y = 5.16


```{R}
# Datensatz anschauen
jackals <- read.table(file = "SW10/jackals.txt", header = TRUE) # Datensatz einlesen
jackals
```

a) Handelt es sich um gepaarte oder ungepaarte Stichproben? Begründen Sie Ihre Antwort.

Ungepaarte Stichproben: Die beiden Stichproben haben keine abhängigkeit zueinander.

b) Formulieren Sie Nullhypothese und Alternativhypothese.

Nullhypothese:  Die männlich Kieferlängen sind gleich lang wie die weiblichen Kieferlängen.
Alternativhypothese: Die Kieferlängen sind nicht gleich lang.

c) Führen Sie den t-Test nun noch mit Hilfe von R durch. Geben Sie den resultierenden p-Wert sowie den daraus folgenden Testentscheid an.

```{R}
t.test(jackals[, "M"], jackals[, "W"])
```

p-Wert: 0.00336 < 0.05 --> Nullhypothese verwerfen

Die männlich Kieferlängen unterscheiden sich signifikant von den weiblichen Kieferlängen.

d) Führen Sie mit Hilfe von R einen Wilcoxon-Test durch. Geben Sie wiederum p-Wert und Testentscheid an.

```{R}
wilcox.test(jackals[, "M"], jackals[, "W"])
```

p-Wert: 0.004845 < 0.05 --> Nullhypothese verwerfen

Die männlich Kieferlängen unterscheiden sich signifikant von den weiblichen Kieferlängen.

e) Falls die Resultate der beiden Tests unterschiedlich ausgefallen wären, welchem
würden Sie eher vertrauen? Weshalb?

Dem Wilcoxon Test, da er nicht annimmt, dass die Daten normalververteilt sind.
Da wir diese Info über nicht haben, müssen wir davon ausgehen, dass sie es nicht sind.
